# -*- coding: utf-8 -*-
"""Bagging_Decision_tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pS92Fg-CQeLDtw5D58O0UzE-dKfAy7Z5
"""

#Bagging with Decision Tree
#import libraries
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

#synthetic data
x,y=make_classification(
n_samples=1000,
n_features=20,
random_state=20
)
print(x,y)

x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=20)

#Initialize the Decision Tree Classifier
base_estimator=DecisionTreeClassifier(random_state=20)

#Initialize the Baggin classifier
bagging_model=BaggingClassifier(
    estimator=base_estimator,
    n_estimators=15,
    random_state=20
)

#train the bagging classifier
bagging_model.fit(x_train,y_train)

#make prediction
y_pred = bagging_model.predict(x_test)

#evaluate Model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy:", {accuracy})