# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzMrPxdGCaIqscSAZZS8-duAghzVVjb8
"""

import pandas as ps
import numpy as np
import matplotlib.pyplot as plt

path='//content/craiglist.csv'
df=ps.read_csv(path)
df.head()

X=df[['condition','odometer','make','year']]
Y=df['price']
print(X,Y)

from sklearn import preprocessing
le= preprocessing.LabelEncoder()
df['condition']=le.fit_transform(df['condition'])
df.head()

print("missing values in each column:")
print(df.isnull().sum())
df = df.dropna(subset=['price'])

from sklearn.impute import SimpleImputer
imputer_median = SimpleImputer(strategy='median')
df['odometer'] = imputer_median.fit_transform(df[['odometer']])

from sklearn.preprocessing import LabelEncoder,StandardScaler
scalar = StandardScaler()
df['odometer'] = scalar.fit_transform(df[['odometer']])

X=df.drop(columns=['price'])
Y=df['price']

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)
print(X_train)
print(X_test)

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)