# -*- coding: utf-8 -*-
"""diabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q1gi-sjbHYiHD1x8Pi71Q01phj5HYK9x
"""

import pandas as pd

df=pd.read_csv('/content/diabetes.csv')
#df

df.head()

X=df[['Pregnancies','Glucose',	'BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age','Outcome']]
Y=df['Outcome']
print(X)
print(Y)

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test=train_test_split(X,Y,test_size=0.2,random_state=0)
#instantiate model
logreg = LogisticRegression()

#fit model

logreg.fit(x_train, y_train)

#prediction of test data
y_pred=logreg.predict(x_test)