# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_Cbh72Z1BLlI2nWdQRXWTARtX5fA6RM
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

path='//content/iris.csv'
df=pd.read_csv(path)
df.head()

from sklearn import preprocessing
le=preprocessing.LabelEncoder()
df['Species']=le.fit_transform(df['Species'])
df.head()

X=df[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
Y=df['Species']
print(X,Y)

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)
print(X_train)
print(X_test)

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,Y_train)
df=np.array([[5.1,3.5,1.4,0.2]])
Y_pred=knn.predict(df)
print(Y_pred)
print(df)

from sklearn.metrics import accuracy_score
Y_pred=knn.predict(X_test)
accuracy=accuracy_score(Y_test,Y_pred)
print(accuracy)

from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logreg.fit(X_train,Y_train)
Y_pred=logreg.predict(X_test)
accuracy=accuracy_score(Y_test,Y_pred)
print(Y_pred)
print(accuracy)