# -*- coding: utf-8 -*-
"""socialnetworking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XQaTYL-AEjHi347n1OnKwjjqevKd_HWV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

path='/content/social_network.csv'
data=pd.read_csv(path)
data.head()

from sklearn import preprocessing
le=preprocessing.LabelEncoder()
data['Gender']=le.fit_transform(data['Gender'])

data.head()

X=data[['Age','EstimatedSalary','Gender']]
Y=data['Purchased']
print(X,Y)

#split X and Y into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)
print(X_train)
print(X_test)

#import the class
from sklearn.linear_model import LogisticRegression
#instantiate the model(using the default parameters)
logreg=LogisticRegression()
#fit the model with data
logreg.fit(X_train,Y_train)
Y_pred =logreg.predict(X_test)
print(Y_pred)